### ISSUE TITLE
Error importing Sass: base and animations files

### ISSUE THREAD

**Issue by elsajyang** [kapoko/delicious-hamburgers#4]
I followed the usage instructions found at [delicious-hamburgers @npmjs](https://www.npmjs.com/package/delicious-hamburgers?activeTab=readme), but I was unable to resolve some imports without editing some files. Since I have not used Sass on any projects, I am unfamiliar with it, so do let me know how best to resolve the imports.

I tried
1. **Plain CSS** (i.e. download the stylesheet and include it in my `.html` file inside `<head>`), which **worked**
2. Install the npm package and import Sass. The package installed smoothly, but **importing the Sass files `base` and the specific animation file brought up errors**.

Instead of the original instructions, which said to import the following:
```
@import "~delicious-hamburgers/scss/base";
@import "~delicious-hamburgers/scss/animations/criss-cross";
```

I had to specify the path (and replaced @import with @use which [Sass prefers](https://sass-lang.com/documentation/at-rules/import))
```
@use "./node_modules/delicious-hamburgers/scss/base";
```
to resolve the error 
```
Error: Can't find stylesheet to import.
@use "~/node_modules/delicious-hamburgers/scss/base";
```

Then, I had to add the line `@import '../base';` (which defines `hamburger-bar()`) to the files in `/node_modules/delicious-hamburgers/scss/animation` (like `_criss-cross.scss`) to resolve the error 
```
Error: Undefined mixin.
@include hamburger-bar();
```

If I import `hamburger.scss` which includes all the animations I'm sure the files compile all fine.

Lastly, would one be able to resize the button?

Thanks so much for creating an awesome set of pure CSS animated hamburger menu buttons!

**Comment by kapoko** [comment]
Are you using Parcel as a bundler? The tilde (~) notation (`@import "~delicious-hamburgers/..."`) doesn't seem to work ([issue](https://github.com/parcel-bundler/parcel/issues/1236)). For parcel using something like `@import "./node_modules/delicious-hamburgers/..."` seems to work fine.

Thanks for pointing out that `@use` will be the preferred method in the future, but `@use` and `@import` work differently when overriding default values. [Here](https://sass-lang.com/documentation/at-rules/use#loading-members) the documentation notes: 
```
Members (variables, functions, and mixins) loaded with @use are only visible in the stylesheet that loads them. 
```
That's why you get the undefined mixin error because `hamburger-bar()` is scoped and not visible from the second imported file.

**So for now**: with this package you'll have to use `@import`, I'd recommend that over editing the plugin files, or importing all animations. I'll have to update this package [sometime before 2022](https://sass-lang.com/blog/the-module-system-is-launched#future-plans) it seems. As a bonus this also means I will be able to make it simpler by using `@use` in the animation files and you won't have to import the base file anymore. Using the plugin would then look something like (**please note this is not supported yet**):

```scss
@use "~delicious-hamburgers/scss/animations/criss-cross" with (
     $hamburger-size: 100px,
     // etc...
);
```
For your second question: Resizing is done by setting the `$hamburger-size` variable before you import the scss files, the default is `50px`. [Check out all the possible variables here](https://github.com/kapoko/delicious-hamburgers#list-of-default-variables). Maybe you tried it already with the `@use` keyword but that unfortunately won't work, because the internal default variable would be scoped to the file and therefore not overridden.

Closing this issue for now but feel free to open it back up if I'm missing anything!
